name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # Cambia esto si usas otra rama principal (ej. master)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate with Firebase
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > $HOME/firebase-key.json

      - name: Deploy to Firebase
        run: firebase deploy --only hosting --token "$(cat $HOME/firebase-key.json)"
